Login = "root"
External = "10.90.36.37"
HostIPs = ["10.90.36.37"]
ProxyAddress = "localhost"
MonitorPort = 10000
Simulation = "TransferCoins"
Servers = 2
Hosts = 20
Debug = 1
DebugTime = false
DebugColor = false
DebugPadding = true
RunWait = "6000s"
Delay = 10
Bandwidth = 1000
Suite = "Ed25519"
PreScript = ""
Tags = ""
