_: &language_go_1_13
  name: "go 1.13"
  language: go
  go: "1.13.x"
_: &language_go_1_14
  name: "go 1.14"
  language: go
  go: "1.14.x"

_: &gen_link_kyber
  pushd external/js/kyber && npm ci && npm run link && popd
_: &get_go
  - gimme 1.13
  - . $HOME/.gimme/envs/go1.13.env

_: &stage_build_go
  script:
    - make -C conode bindist tooldist
    - GO111MODULE=on go build ./...

dist: trusty

stages:
  - lint
  - build
  - test

jobs:
  include:
    - stage: lint
      name: "protobuf"
      language: minimal
      script: make test_proto
    - <<: *language_go_1_13
      script:
        - go mod tidy && [ -z "$(git status --porcelain)" ]
        - make -C conode verify
        - GO111MODULE=on make test_{fmt,lint}
    - <<: *language_go_1_14
      script:
        - make -C conode verify
        - GO111MODULE=on make test_{fmt,lint}

    - stage: build
      <<: *stage_build_go
      <<: *language_go_1_13
    - <<: *stage_build_go
      <<: *language_go_1_14

    - stage: test
      <<: *language_go_1_13
      script: GO111MODULE=on go test -short -v ./byzcoin

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
