_: &language_go_1_13
  name: "go 1.13"
  language: go
  go: "1.13.x"
_: &language_js
  language: node_js
  node_js: "lts/*"

_: &gen_link_kyber
  pushd external/js/kyber && npm ci && npm run link && popd
_: &get_go
  - gimme 1.12.16
  - . $HOME/.gimme/envs/go1.12.16.env

_: &stage_build_go
  script:
    - make -C conode bindist tooldist
    - GO111MODULE=on go build ./...

dist: trusty

stages:
  - lint
  - build
  - test

jobs:
  include:
    - stage: lint
      name: "protobuf"
      language: minimal
      script: make test_proto
    - <<: *language_go_1_13
      script:
        - make -C conode verify
        - GO111MODULE=on make test_{fmt,lint}

    - stage: build
      name: "go 1.12"
      language: go
      go: "1.12.x"
      <<: *stage_build_go
    - <<: *stage_build_go
      <<: *language_go_1_13

    - stage: test
      <<: *language_go_1_13
      script: GO111MODULE=on go test -short -v ./byzcoin

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
