Simulation = "TransferCoins"
Servers = 2
Bf = 4
Rounds = 3
RunWait = "6000s"
Suite = "Ed25519"
Accounts = 5
# Keep the different columns in case someboday wants to run another battery
# of tests

Keep,   Transactions, BatchSize,  Hosts,  Delay, BlockInterval
true,   20,          5,          5,     10,    "1s"



#true,   20,          5,          5,     10,    "1s"
#true,   20,          10,          5,     10,    "1s"
#true,   200,          1,          5,     10,    "1s"
#true,   200,          5,          5,     10,    "1s"
#true,   200,          10,          5,     10,    "1s"
#true,   2000,          1,          5,     10,    "1s"
#true,   2000,          2,          5,     10,    "1s"
#true,   2000,          5,          5,     10,    "1s"
#true,   2000,          10,          5,     10,    "1s"
# true,   200,          10,         10,     10,    "2s"
# true,   200,          20,         10,     10,    "2s"

